#print("hello sir......",end="\t")
#print("hello world....")
#print("\t\t\t\t Bio-Data")

print("\n\t=================================================================")
print("\t\t\t AKS UNIVERSITY, SATNA (M.P.)")
print("\t=================================================================\n")

print("\t|Name:\tHardik Jain\t",a,"\t\tCourse:\tB.Tech (AI & DS)  |")
print("\t|Roll No:063\t\t\t\tBranch:\tCSE   \t\t  |")
print("\t|FName:\tXYZ\t\t\t\tSemester:6th  \t\t  |")
print("\t|MName:\tXYZ\t\t")
print("\t|-----------------------------------------------------------------|")
print("\t|Subject\t\tMin Marks\tMarks Obtain\tTotal Mark|")
print("\t|-----------------------------------------------------------------|")
print("\t|Machine Learning\t33\t\t78\t\t100\t  |")
print("\t|NLP\t\t\t33\t\t74\t\t100\t  |")
print("\t|Artificia Intelligence\t33\t\t81\t\t100\t  |")
print("\t|Data Analytics\t\t33\t\t76\t\t100\t  |")
print("\t|Software Engineering\t33\t\t72\t\t100\t  |")
print("\t|Project \t\t40\t\t85\t\t100\t  |")
print("\t|-----------------------------------------------------------------|")
print("\t\t\t\tTotal\t\t466\t\t600")
print("\tResult:\tPASS")
print("\tGrade:\tA\n")

print("\t-----------------------------------------------------------------")
print("\tDate:\t04/02/2026\t\t\tController of Examination")
print("\t=================================================================")
 
